### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by ROCKIv** [AggFerret/lithium.rip#1]
Please help to compile it, i have a lot of errors.

Please contact discord: me cambie de cuenta#9313

i have 0,15 usd in paypal to give lol

**Comment by dystoferris** [comment]
Hello!

In order to compile Lithium Lite, you'll need to select "Lithium Lite (no auth)" in the "Lithium Lite (latest)" folder. I recommend opening "Lithium Lite (no auth)" in CLion by JetBrains.

**Comment by Cromaxxxx** [comment]
Besides CLion, what else to download, since it gives me error when I try to compile it.

**Comment by Cromaxxxx** [comment]
> Hello!
> 
> In order to compile Lithium Lite, you'll need to select "Lithium Lite (no auth)" in the "Lithium Lite (latest)" folder. I recommend opening "Lithium Lite (no auth)" in CLion by JetBrains.

Besides CLion, what else should I download? because when I try to compile it, I get several errors
