### ISSUE TITLE
this code is fucking dogshit

### ISSUE THREAD

**Issue by through** [AggFerret/lithium.rip#2]
https://github.com/AggFerret/lithium.rip/blob/f05cf654b374ed4764640a5fb23b85e135d19e58/Lithium%20Lite%202.0%20(with%20auth)/Lithium%20Lite%202.0/fly.cpp#L33

**Comment by AggFerret** [comment]
Ok? I didn't code this? epic did (main.cpp).

**Comment by through** [comment]
yes you did what

**Comment by AggFerret** [comment]
No I did not, like I said if you read main.cpp this was all coded by epic. This is a source code leak.

**Comment by AggFerret** [comment]
Troll.
