### ISSUE TITLE
Question RE: Compiling

### ISSUE THREAD

**Issue by ghost** [AggFerret/lithium.rip#3]
Been having some issues with the sources, almost all on compile.

Lithium lite 2.0 (NO AUTH) is completely and totally broken for me, i have 320 errors. 
The old lithium with no auth is a bit better, but it has a good few deprecated functions.
Do you have a fixed source? also, the .sln's seem to be pointing at wrong things, it expects another folder called lith-lite inside the source folder which when made just expects another one. Try and build this source off your github, curious whether it's me being dumb or if the source is fucked

**Comment by dystoferris** [comment]
My apologies, i’m currently on vacation and I fucked something up when
uploading this shit to GitHub. It was like 4 am and I hadn’t slept in like
2 days.

I’ll fix it all as soon as I’m home.

**Comment by ghost** [comment]
You're fine! I really appreciate your response, I wasn't expecting anything. Enjoy your vacation :>

**Comment by ghost** [comment]
also, seeing as i'm not really active on git, if you want to communicate about this and development in general my discord is celestial#1000
